### ISSUE TITLE
Restart button has stopped appearing on FF Beta-Developer 69 and Nightly 70

### ISSUE THREAD

**Issue by siffegh** [Sporif/firefox-quantum-userchromejs#2]
Subject says it all. I have the latest userChrome.xml and text from userChrome.css.

**Comment by Sporif** [comment]
And you're using the latest version of https://gist.github.com/Sporif/ad6e917d87787491538bac80d3c8918c?

**Comment by siffegh** [comment]
Apparently, I wasn't using that version; I still had the one which produced the blue icon. Working everywhere now, thanks.

**Comment by siffegh** [comment]
It's gone again on Nightly v70.x
